In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [21]:
df=pd.read_csv('Iris.csv')

In [22]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [23]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [24]:
X=df.drop(columns=['Species','Id'])
y=df['Species']

In [25]:
le=LabelEncoder()

In [27]:
y_int=le.fit_transform(df['Species'])

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y_int, test_size=0.20, random_state=42,stratify=y_int)

In [33]:
scaler=StandardScaler()

In [37]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [40]:
per=Perceptron(max_iter=10000,random_state=42)
per.fit(X_train_scaled,y_train)

Perceptron(max_iter=10000, random_state=42)

In [45]:
y_pred_per=per.predict(X_test_scaled)

In [46]:
accuracy_score(y_test,y_pred_per)

0.8666666666666667

In [51]:
y_train_cat=to_categorical(y_train,num_classes=3)
y_test_cat=to_categorical(y_test,num_classes=3)

In [55]:
model=Sequential([Dense(16,input_dim=4,activation='relu'),
                 Dense(8,activation='relu'),
                 Dense(3,activation='softmax')
                 ])

In [63]:
model.compile(optimizer='adam',loss='CategoricalCrossentropy',metrics=['accuracy'])

In [64]:
history=model.fit(X_train_scaled,y_train_cat,epochs=100,batch_size=8,validation_split=0.2)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.3021 - loss: 1.1034 - val_accuracy: 0.4167 - val_loss: 1.0649
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3229 - loss: 1.0532 - val_accuracy: 0.4583 - val_loss: 1.0236
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4583 - loss: 1.0121 - val_accuracy: 0.5833 - val_loss: 0.9837
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5625 - loss: 0.9709 - val_accuracy: 0.7083 - val_loss: 0.9474
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.9344 - val_accuracy: 0.7500 - val_loss: 0.9115
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6250 - loss: 0.8968 - val_accuracy: 0.7500 - val_loss: 0.8770
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6250 - loss: 0.8600 - val_accuracy: 0.7500 - val_loss: 0.8406
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6354 - loss: 0.8219 - val_accuracy: 0.7083 - val_loss: 0.8045
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7083 - loss: 0.7841 - val_accuracy: 0.7500 - val_loss: 0.7678
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7812 - loss: 0.7449 - val_accuracy: 0.7500 - val_loss: 0.7318
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7812 - loss: 0.7051 - val_accuracy: 0.7500 - val_loss: 0.6968
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8021 - loss: 0.6662 - val_accuracy: 0.7500 - val_loss: 0.6632
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.6274 - val_accuracy: 0.7500 - val_loss: 0.6294
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.5908 - val_accuracy: 0.7917 - val_loss: 0.5970
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.5558 - val_accuracy: 0.7917 - val_loss: 0.5681
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.5232 - val_accuracy: 0.7917 - val_loss: 0.5435
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.4928 - val_accuracy: 0.7917 - val_loss: 0.5208
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.4670 - val_accuracy: 0.7500 - val_loss: 0.5025
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.4419 - val_accuracy: 0.7500 - val_loss: 0.4856
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.4214 - val_accuracy: 0.7500 - val_loss: 0.4688
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8438 - loss: 0.4046 - val_accuracy: 0.7500 - val_loss: 0.4578
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.3886 - val_accuracy: 0.7500 - val_loss: 0.4439
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.3753 - val_accuracy: 0.7500 - val_loss: 0.4347
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.3626 - val_accuracy: 0.7500 - val_loss: 0.4253
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8542 - loss: 0.3535 - val_accuracy: 0.7500 - val_loss: 0.4193
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8646 - loss: 0.3441 - val_accuracy: 0.7917 - val_loss: 0.4039
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8646 - loss: 0.3351 - val_accuracy: 0.7500 - val_loss: 0.3996
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.3257 - val_accuracy: 0.7917 - val_loss: 0.3904
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.3191 - val_accuracy: 0.7917 - val_loss: 0.3809
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.3122 - val_accuracy: 0.7917 - val_loss: 0.3759
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - loss: 0.3055 - val_accuracy: 0.8333 - val_loss: 0.3683
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2994 - val_accuracy: 0.8333 - val_loss: 0.3588
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2942 - val_accuracy: 0.8333 - val_loss: 0.3486
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2885 - val_accuracy: 0.8750 - val_loss: 0.3420
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2831 - val_accuracy: 0.8750 - val_loss: 0.3343
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2779 - val_accuracy: 0.8750 - val_loss: 0.3322
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2728 - val_accuracy: 0.8750 - val_loss: 0.3264
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2678 - val_accuracy: 0.8750 - val_loss: 0.3178
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2633 - val_accuracy: 0.8750 - val_loss: 0.3101
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.2587 - val_accuracy: 0.8750 - val_loss: 0.3026
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.2557 - val_accuracy: 0.8750 - val_loss: 0.2889
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8958 - loss: 0.2498 - val_accuracy: 0.8750 - val_loss: 0.2857
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8958 - loss: 0.2460 - val_accuracy: 0.8750 - val_loss: 0.2818
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8958 - loss: 0.2419 - val_accuracy: 0.8750 - val_loss: 0.2721
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8958 - loss: 0.2376 - val_accuracy: 0.8750 - val_loss: 0.2661
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8958 - loss: 0.2341 - val_accuracy: 0.8750 - val_loss: 0.2630
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8958 - loss: 0.2298 - val_accuracy: 0.8750 - val_loss: 0.2559
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8958 - loss: 0.2253 - val_accuracy: 0.8750 - val_loss: 0.2477
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8958 - loss: 0.2226 - val_accuracy: 0.8750 - val_loss: 0.2360
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8958 - loss: 0.2196 - val_accuracy: 0.8750 - val_loss: 0.2351
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8958 - loss: 0.2156 - val_accuracy: 0.8750 - val_loss: 0.2260
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9062 - loss: 0.2107 - val_accuracy: 0.9167 - val_loss: 0.2201
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9062 - loss: 0.2079 - val_accuracy: 0.9167 - val_loss: 0.2119
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9062 - loss: 0.2044 - val_accuracy: 0.9167 - val_loss: 0.2106
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9062 - loss: 0.2003 - val_accuracy: 0.9167 - val_loss: 0.2043
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.1973 - val_accuracy: 0.9583 - val_loss: 0.1953
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.1942 - val_accuracy: 0.9583 - val_loss: 0.1870
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9271 - loss: 0.1900 - val_accuracy: 0.9583 - val_loss: 0.1834
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9271 - loss: 0.1872 - val_accuracy: 0.9583 - val_loss: 0.1765
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9271 - loss: 0.1827 - val_accuracy: 0.9583 - val_loss: 0.1710
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9375 - loss: 0.1808 - val_accuracy: 0.9583 - val_loss: 0.1598
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1752 - val_accuracy: 0.9583 - val_loss: 0.1589
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1732 - val_accuracy: 0.9583 - val_loss: 0.1547
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1686 - val_accuracy: 0.9583 - val_loss: 0.1450
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1654 - val_accuracy: 0.9583 - val_loss: 0.1367
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1616 - val_accuracy: 0.9583 - val_loss: 0.1330
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1588 - val_accuracy: 0.9583 - val_loss: 0.1258
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1558 - val_accuracy: 1.0000 - val_loss: 0.1213
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1522 - val_accuracy: 1.0000 - val_loss: 0.1170
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1490 - val_accuracy: 1.0000 - val_loss: 0.1147
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9479 - loss: 0.1456 - val_accuracy: 1.0000 - val_loss: 0.1114
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1431 - val_accuracy: 1.0000 - val_loss: 0.1053
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1405 - val_accuracy: 1.0000 - val_loss: 0.1032
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1382 - val_accuracy: 1.0000 - val_loss: 0.0971
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1358 - val_accuracy: 1.0000 - val_loss: 0.0955
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1331 - val_accuracy: 1.0000 - val_loss: 0.0927
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1299 - val_accuracy: 1.0000 - val_loss: 0.0893
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1274 - val_accuracy: 1.0000 - val_loss: 0.0834
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1249 - val_accuracy: 1.0000 - val_loss: 0.0809
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1226 - val_accuracy: 1.0000 - val_loss: 0.0798
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9479 - loss: 0.1205 - val_accuracy: 1.0000 - val_loss: 0.0761
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1197 - val_accuracy: 1.0000 - val_loss: 0.0759
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1162 - val_accuracy: 1.0000 - val_loss: 0.0710
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1142 - val_accuracy: 1.0000 - val_loss: 0.0671
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1123 - val_accuracy: 1.0000 - val_loss: 0.0665
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1101 - val_accuracy: 1.0000 - val_loss: 0.0640
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1082 - val_accuracy: 1.0000 - val_loss: 0.0619
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1070 - val_accuracy: 1.0000 - val_loss: 0.0584
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1046 - val_accuracy: 1.0000 - val_loss: 0.0571
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1034 - val_accuracy: 1.0000 - val_loss: 0.0567
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9583 - loss: 0.1009 - val_accuracy: 1.0000 - val_loss: 0.0541
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.1006 - val_accuracy: 1.0000 - val_loss: 0.0517
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.0983 - val_accuracy: 1.0000 - val_loss: 0.0502
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.0954 - val_accuracy: 1.0000 - val_loss: 0.0498
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.0944 - val_accuracy: 1.0000 - val_loss: 0.0486
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.0932 - val_accuracy: 1.0000 - val_loss: 0.0467
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.0916 - val_accuracy: 1.0000 - val_loss: 0.0459
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.0918 - val_accuracy: 1.0000 - val_loss: 0.0436
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.0900 - val_accuracy: 1.0000 - val_loss: 0.0430
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9583 - loss: 0.0877 - val_accuracy: 1.0000 - val_loss: 0.0407